version: latest
services:
  lbg-app:
    image: lbg-app:${version}
    build: .
    environment:
      PORT: ${PORT}
    ports:
      - target: ${PORT}
        published: 80
        protocol: tcp
      
