version: latest
services:
  flask-app:
    build:
    ports:
      -target: 5000
      published: 5000
      protocol: tcp
      
  nginx:
    image: nginx:alpine
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
      -type: bind
      source: ./nginx.conf
      target: /etc/nginx.conf
      
